---

######################################################################################################################
###                                                                                                                ###
###     ClickHouse tracks changes in the config files and reloads users and clusters configurations on the fly     ###
###     You can add or change users, clusters and their settings without restarting the server                     ###
###     For remote_servers the server reads config immediately after the request                                   ###
###                                                                                                                ###
######################################################################################################################

- name: CLICKHOUSE CONFIG TASK | Ensure That Directories Exist [Docker]
  file:
    path: "{{ item.host_dir }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ clickhouse_directories_container }}"
  tags: [configure_clickhouse]

- name: CLICKHOUSE CONFIG TASK | Get a List of All Shards In the ClickHouse Cluster
  set_fact:
    clickhouse_shard_numbers: "{{ hostvars[inventory_hostname]['clickhouse_cluster'] | json_query(query) | unique | sort }}"
  vars:
    query: "shards[*].ch_shard"
  tags: [configure_clickhouse]

- name: CLICKHOUSE CONFIG TASK | Show ClickHouse Shards
  debug:
    msg: "{{ clickhouse_shard_numbers }}"
  tags: [configure_clickhouse]

- name: CLICKHOUSE CONFIG TASK | Ensure That Config Files Exist [Docker]
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ clickhouse_files_container }}"
  tags: [configure_clickhouse]