---

- name: CLICKHOUSE FORCE RESTART | Restart ClickHouse [Host]
  systemd:
    name: "{{ clickhouse_systemd_service_name }}"
    state: "restarted"
  when:
    - clickhouse_installation_type == "host"
    - clickhouse_installed_docker == false
  tags: [always]

- name: CLICKHOUSE FORCE RESTART | Restart ClickHouse [Docker]
  command: "docker restart {{ clickhouse_config['docker_opts']['container_name'] }}"
  when:
    - clickhouse_installation_type == "docker"
    - clickhouse_installed_host == false
  tags: [always]

- name: CLICKHOUSE FORCE RESTART | Clickhouse Healthcheck [Secure]
  uri:
    url: "{{ clickhouse_http_healthcheck_host }}:{{ clickhouse_https_port }}/ping"
    validate_certs: false
    status_code: 200
  register: ch_result
  until: ch_result.status == 200
  retries: "{{ clickhouse_config['global']['status_check_retries'] }}"
  delay: "{{ clickhouse_config['global']['status_check_delay'] }}"
  when:
    - clickhouse_ssl['http_interface_ssl_enable'] is defined
    - clickhouse_ssl['http_interface_ssl_enable'] == true
  tags: [always]

- name: CLICKHOUSE FORCE RESTART | Clickhouse Healthcheck [Insecure]
  uri:
    url: "{{ clickhouse_http_healthcheck_host }}:{{ clickhouse_http_port }}/ping"
    status_code: 200
  register: ch_result
  until: ch_result.status == 200
  retries: "{{ clickhouse_config['global']['status_check_retries'] }}"
  delay: "{{ clickhouse_config['global']['status_check_delay'] }}"
  when: ( clickhouse_ssl['http_interface_ssl_enable'] is defined and clickhouse_ssl['http_interface_ssl_enable'] == false ) or ( clickhouse_ssl['http_interface_ssl_enable'] is not defined )
  tags: [always]